baseURL: 'https://anilahsu.github.io/Blog/'
languageCode: zh-TW
title: Anila Blog
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-9Y9CGTK6N1

minify:
    disableXML: true
    minifyOutput: true

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Anila blog
    description: "Pleased to meet you this is Anila's Blog : )"
    keywords: [Blog, Portfolio, PaperMod]
    author: Anila
    # author: ["Me", "You"] # multiple authors
    images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    disableSpecial1stPost: false
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    assets:
        disableHLJS: false # to disable highlight.js
        disableFingerprinting: true
        favicon: "favicon.png"
        favicon16x16: "favicon.png"
        favicon32x32: "favicon.png"
        apple_touch_icon: "favicon.png"
        safari_pinned_tab: "favicon.png"

    label:
        text: "Home"
        # icon: /apple-touch-icon.png
        # iconHeight: 35

    # profile-mode
    profileMode:
        enabled: true # needs to be explicitly set
        title: Anila Blog
        subtitle: "Hi. Glad to meet you!"
        imageUrl: "profile.jpg"
        # imageWidth: 120
        # imageHeight: 120
        # imageTitle: my image
        buttons:
            - name: Posts
              url: posts



    # home-info mode
    homeInfoParams:
        Title: "Hi there \U0001F44B"
        Content: Welcome to my blog

    socialIcons:
        - name: email
          url: "yashuhsu.anila@gmail.com"
        - name: linkedin
          url: "https://www.linkedin.com/in/AnilaHsu"          
        - name: github
          url: "https://github.com/AnilaHsu"
        - name: twitter
          url: "https://twitter.com/AnilaHsu"
        - name: Instagram
          url: "https://www.instagram.com/anila_hsu/"


    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: false # hide on single page

    editPost:
        URL: ""
        Text: "My Web site " # edit text
        appendFilePath: true # to append file path to Edit link

    # for search
    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]
menu:
    main:
        - identifier: Posts
          name: Posts
          url: /posts/
          weight: 5
        - identifier: Categories
          name: Categories
          url: /categories/
          weight: 10
        - identifier: Tags
          name: Tags
          url: /tags/
          weight: 20
Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        style: tango